services:
  - type: web
    name: e-vartalap
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /health.php
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_URL
        value: https://e-vartalap.onrender.com
      - key: AUTO_INIT_DB
        value: true
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_SSL_MODE
        value: verify-ca
      - key: DB_SSL_CA_CERT
        sync: false
